apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferencepoc-deployment
  labels:
    app: inferencepoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inferencepoc
  template:
    metadata:
      labels:
        app: inferencepoc
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: inferencepoc-sa
      containers:
        - name: inferencepoc
          image: 269538733491.dkr.ecr.us-west-2.amazonaws.com/inferencepoc:latest-amd64
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
